version: '3.7'
networks:
  cicd-network:
    driver: bridge

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab
    networks:
      - cicd-network
    ports:
      - "8581:80"
      - "4433:443"
      - "2222:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - /host_mnt/d/analisa/YBoilerplate:/home/gitlab/YBoilerplate
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 1024M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    hostname: jenkins
    networks:
      - cicd-network
    ports:
      - "8582:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /host_mnt/d/analisa/YBoilerplate:/var/jenkins_home/workspace/YBoilerplate
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 3000M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  build-server:
    image: build-server:latest
    container_name: build-server
    hostname: build-server
    networks:
      - cicd-network
    volumes:
      - /host_mnt/d/analisa/YBoilerplate:/home/build/YBoilerplate
    working_dir: /home/build/YBoilerplate
    command: /bin/bash -c "sleep infinity"
    ports:
      - "8580:8080"
    build:
      context: .
      dockerfile: Dockerfile-build-server
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 1024M
    healthcheck:
      test: ["CMD-SHELL", "ls /home/build/YBoilerplate || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins-home: